### ISSUE TITLE
Vulnerability in the package

### ISSUE THREAD

**Issue by juanjoDiaz** [DavidWells/markdown-magic#41]
Reported by `npm audit`

│ Moderate             │ Regular Expression Denial of Service                                                │
│ Package               │ underscore.string                                                                                │
│ Patched in           │ >=3.3.5                                                                                                 │
│ Dependency of   │ markdown-magic [dev]                                                                       │
│ Path                     │ markdown-magic > markdown-toc > remarkable > argparse >      │
│                              │ underscore.string                                                                                │
│ More info             │ https://npmjs.com/advisories/745                                                     │

**Comment by tripflex** [comment]
I can confirm this as well, showing on mine that i'm using for generating awesome list https://github.com/tripflex/awesome-mongoose-os

**Comment by DavidWells** [comment]
Thanks for the report

Do you know if this is fixed upstream in these `markdown-toc > remarkable > argparse`?

**Comment by forresst** [comment]
Here is the current state:

**argparse**: no longer uses underscore since **February 19, 2015** ([version 1.0.0](https://github.com/nodeca/argparse/commit/ffc165b39332bbd85474adb9afccad7d080aac1c))

**remarkable**: a version change was made [from 0.1.15 to 1.0.10]((https://github.com/jonschlinkert/remarkable/commit/76df13bbb01180ac5247cdf81063eb00406397da)) on **July 21, 2019** but remarkable was not versioned (only the master contains the modification)

**markdown-toc**: uses remarkable (version 1.7.1) since version 1.0.0 of markdown-toc. Note: markdown-toc has an issue for [this vulnerability](https://github.com/jonschlinkert/markdown-toc/issues/135)

**Comment by DavidWells** [comment]
Thanks for the insight!

How can we fix this? (Hopefully without forking and maintaining all the upstream deps?)

Are folks using markdown-magic on a server where this ddos vulnerability would be an issue?

**Comment by DavidWells** [comment]
Fixed with `markdown-magic@2.3.0`
